version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jchapman127
  assignees:
  - jchapman127
  allow:
  - dependency-type: direct
  - dependency-type: indirect
