trigger:
- master
pr:
- master

jobs:
# Check formatting
- job: rustfmt
  displayName: Check rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ci/azure-install-rust.yml
    parameters:
      rustup_toolchain: stable
  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt
  - script:
      cargo fmt --all -- --check
    displayName: Check formatting

# Test
- job: test
  displayName: Test
  strategy:
    matrix:
      linux:
        imageName: ubuntu-16.04
        rustup_toolchain: stable
      macos:
        imageName: macos-10.13
        rustup_toolchain: stable
      windows:
        imageName: vs2017-win2016
        rustup_toolchain: stable
  pool:
    vmImage: $(imageName)
  steps:
  - template: ci/azure-install-rust.yml
    parameters:
      rustup_toolchain: $(rustup_toolchain)
  - script: cargo test
    displayName: Cargo test
